// 지구본 lab 국가 메타데이터(한/영 이중언어). world.json 영어명(properties.n)을 키로.
// 코드맵(LANG/GOV/ECON)으로 반복 번역을 압축 → 국가별로는 코드만 참조. desc만 {ko,en} 직접.
// ISO2 → 유니코드 지역표시문자로 국기 이모지 생성.
export function flagEmoji(iso2){ if(!iso2||iso2.length!==2)return ''; const A=0x1F1E6; return String.fromCodePoint(A+(iso2.charCodeAt(0)-65))+String.fromCodePoint(A+(iso2.charCodeAt(1)-65)); }

const LANG={ ko:['한국어','Korean'], en:['영어','English'], ja:['일본어','Japanese'], zh:['중국어','Chinese'],
  es:['스페인어','Spanish'], pt:['포르투갈어','Portuguese'], fr:['프랑스어','French'], de:['독일어','German'],
  it:['이탈리아어','Italian'], nl:['네덜란드어','Dutch'], ru:['러시아어','Russian'], ar:['아랍어','Arabic'],
  hi:['힌디어','Hindi'], ur:['우르두어','Urdu'], bn:['벵골어','Bengali'], fa:['페르시아어','Persian'],
  tr:['튀르키예어','Turkish'], he:['히브리어','Hebrew'], th:['타이어','Thai'], vi:['베트남어','Vietnamese'],
  id:['인도네시아어','Indonesian'], ms:['말레이어','Malay'], fil:['필리핀어','Filipino'], my:['버마어','Burmese'],
  km:['크메르어','Khmer'], lo:['라오어','Lao'], mn:['몽골어','Mongolian'], ne:['네팔어','Nepali'],
  si:['싱할라어','Sinhala'], ta:['타밀어','Tamil'], dz:['종카어','Dzongkha'], ps:['파슈토어','Pashto'],
  ka:['조지아어','Georgian'], hy:['아르메니아어','Armenian'], az:['아제르바이잔어','Azerbaijani'],
  kk:['카자흐어','Kazakh'], uz:['우즈베크어','Uzbek'], sv:['스웨덴어','Swedish'], no:['노르웨이어','Norwegian'],
  da:['덴마크어','Danish'], fi:['핀란드어','Finnish'], pl:['폴란드어','Polish'], uk:['우크라이나어','Ukrainian'],
  el:['그리스어','Greek'], cs:['체코어','Czech'], hu:['헝가리어','Hungarian'], ro:['루마니아어','Romanian'],
  bg:['불가리아어','Bulgarian'], sr:['세르비아어','Serbian'], hr:['크로아티아어','Croatian'], sk:['슬로바키아어','Slovak'],
  sl:['슬로베니아어','Slovenian'], lt:['리투아니아어','Lithuanian'], lv:['라트비아어','Latvian'], et:['에스토니아어','Estonian'],
  is:['아이슬란드어','Icelandic'], sq:['알바니아어','Albanian'], mk:['마케도니아어','Macedonian'], mt:['몰타어','Maltese'],
  sw:['스와힐리어','Swahili'], am:['암하라어','Amharic'], zu:['줄루어','Zulu'], af:['아프리칸스어','Afrikaans'],
  ber:['베르베르어','Berber'], mg:['마다가스카르어','Malagasy'], qu:['케추아어','Quechua'], mi:['마오리어','Maori'],
  gn:['과라니어','Guarani'], tet:['테툼어','Tetum'], dv:['디베히어','Dhivehi'], to:['통가어','Tongan'],
  sm:['사모아어','Samoan'], fj:['피지어','Fijian'], tpi:['톡피신','Tok Pisin'], nl2:['','']
};
const GOV={ libdem:['자유민주주의','Liberal democracy'], presrep:['대통령제 공화국','Presidential republic'],
  parlrep:['의원내각제 공화국','Parliamentary republic'], semi:['이원집정부제 공화국','Semi-presidential republic'],
  constmon:['입헌군주제','Constitutional monarchy'], absmon:['전제군주제','Absolute monarchy'],
  fedpres:['대통령제 연방공화국','Federal presidential republic'], fedparl:['의원내각제 연방공화국','Federal parliamentary republic'],
  fedmon:['연방 군주제','Federal monarchy'], onep:['일당제 사회주의','One-party socialist state'],
  theo:['신정','Theocracy'], mil:['군정','Military government'], comm:['공산주의 국가','Communist state'],
  fedconst:['입헌군주제 연방국','Federal constitutional monarchy'], directdem:['직접민주주의 연방','Federal direct democracy'],
  dep:['자치령','Autonomous territory'] };
const ECON={ cap:['자본주의','Capitalism'], socmkt:['사회주의 시장경제','Socialist market economy'],
  plan:['계획경제','Planned economy'], mixed:['혼합경제','Mixed economy'], welfare:['자본주의(복지국가)','Capitalism (welfare state)'],
  oil:['자본주의(석유)','Capitalism (oil-based)'], socmkt2:['사회적 시장경제','Social market economy'] };

// desc: {ko, en}. langs: LANG 코드 배열(최대 3 표시). gov/econ: 코드.
export const COUNTRY = {
  'South Korea':{iso2:'KR',ko:'대한민국',en:'Republic of Korea',langs:['ko'],gov:'libdem',econ:'cap',desc:{ko:'동아시아의 반도 국가로 빠른 경제성장과 K-문화로 유명해요.',en:'An East Asian peninsular nation known for rapid growth and K-culture.'}},
  'North Korea':{iso2:'KP',ko:'조선민주주의인민공화국',en:"Democratic People's Republic of Korea",langs:['ko'],gov:'onep',econ:'plan',desc:{ko:'한반도 북부의 사회주의 국가로 폐쇄적 체제를 유지해요.',en:'A socialist state in the north of the Korean peninsula with a closed system.'}},
  'Japan':{iso2:'JP',ko:'일본국',en:'Japan',langs:['ja'],gov:'constmon',econ:'cap',desc:{ko:'네 개의 큰 섬으로 이뤄진 동아시아의 경제 강국이에요.',en:'An East Asian economic power made up of four main islands.'}},
  'China':{iso2:'CN',ko:'중화인민공화국',en:"People's Republic of China",langs:['zh'],gov:'onep',econ:'socmkt',desc:{ko:'세계에서 인구가 가장 많은 대국 중 하나이자 아시아의 중심이에요.',en:'One of the world\'s most populous nations and a center of Asia.'}},
  'Taiwan':{iso2:'TW',ko:'대만',en:'Taiwan',langs:['zh'],gov:'libdem',econ:'cap',desc:{ko:'동아시아의 섬으로 반도체 산업이 크게 발달했어요.',en:'An East Asian island with a highly developed semiconductor industry.'}},
  'Mongolia':{iso2:'MN',ko:'몽골',en:'Mongolia',langs:['mn'],gov:'parlrep',econ:'cap',desc:{ko:'광활한 초원과 유목 문화로 알려진 내륙국이에요.',en:'A landlocked country known for vast steppes and nomadic culture.'}},
  'Vietnam':{iso2:'VN',ko:'베트남 사회주의공화국',en:'Socialist Republic of Vietnam',langs:['vi'],gov:'onep',econ:'socmkt',desc:{ko:'동남아시아의 긴 해안선을 가진 나라예요.',en:'A Southeast Asian country with a long coastline.'}},
  'Thailand':{iso2:'TH',ko:'타이 왕국',en:'Kingdom of Thailand',langs:['th'],gov:'constmon',econ:'cap',desc:{ko:'불교문화와 관광으로 유명한 동남아 국가예요.',en:'A Southeast Asian nation famed for Buddhist culture and tourism.'}},
  'Philippines':{iso2:'PH',ko:'필리핀 공화국',en:'Republic of the Philippines',langs:['fil','en'],gov:'presrep',econ:'cap',desc:{ko:'7천여 개의 섬으로 이뤄진 동남아 군도 국가예요.',en:'A Southeast Asian archipelago of over 7,000 islands.'}},
  'Indonesia':{iso2:'ID',ko:'인도네시아 공화국',en:'Republic of Indonesia',langs:['id'],gov:'presrep',econ:'cap',desc:{ko:'세계 최대의 섬나라로 수많은 화산과 문화가 있어요.',en:'The world\'s largest island nation, with many volcanoes and cultures.'}},
  'Malaysia':{iso2:'MY',ko:'말레이시아',en:'Malaysia',langs:['ms','en'],gov:'fedconst',econ:'cap',desc:{ko:'말레이반도와 보르네오섬에 걸친 다민족 국가예요.',en:'A multiethnic nation spanning the Malay Peninsula and Borneo.'}},
  'Singapore':{iso2:'SG',ko:'싱가포르 공화국',en:'Republic of Singapore',langs:['en','zh','ms'],gov:'parlrep',econ:'cap',desc:{ko:'작지만 금융·무역이 발달한 도시국가예요.',en:'A small city-state with advanced finance and trade.'}},
  'India':{iso2:'IN',ko:'인도 공화국',en:'Republic of India',langs:['hi','en'],gov:'fedparl',econ:'cap',desc:{ko:'남아시아의 거대한 인구와 다양한 문화를 지닌 나라예요.',en:'A South Asian country with a huge population and great diversity.'}},
  'Pakistan':{iso2:'PK',ko:'파키스탄 이슬람공화국',en:'Islamic Republic of Pakistan',langs:['ur','en'],gov:'fedparl',econ:'cap',desc:{ko:'남아시아의 인더스 문명 발상지예요.',en:'South Asian home of the ancient Indus Valley civilization.'}},
  'Bangladesh':{iso2:'BD',ko:'방글라데시 인민공화국',en:"People's Republic of Bangladesh",langs:['bn'],gov:'parlrep',econ:'cap',desc:{ko:'갠지스 삼각주에 자리한 인구 밀집 국가예요.',en:'A densely populated country on the Ganges delta.'}},
  'Sri Lanka':{iso2:'LK',ko:'스리랑카 민주사회주의공화국',en:'Democratic Socialist Republic of Sri Lanka',langs:['si','ta'],gov:'presrep',econ:'cap',desc:{ko:'인도양의 섬나라로 홍차가 유명해요.',en:'An Indian Ocean island nation famous for black tea.'}},
  'Nepal':{iso2:'NP',ko:'네팔',en:'Nepal',langs:['ne'],gov:'fedparl',econ:'cap',desc:{ko:'히말라야와 에베레스트로 유명한 나라예요.',en:'Home of the Himalayas and Mount Everest.'}},
  'Bhutan':{iso2:'BT',ko:'부탄 왕국',en:'Kingdom of Bhutan',langs:['dz'],gov:'constmon',econ:'mixed',desc:{ko:'히말라야의 작은 왕국으로 국민총행복(GNH)으로 유명해요.',en:'A small Himalayan kingdom known for Gross National Happiness.'}},
  'Myanmar':{iso2:'MM',ko:'미얀마 연방공화국',en:'Republic of the Union of Myanmar',langs:['my'],gov:'mil',econ:'mixed',desc:{ko:'동남아시아의 불교문화 국가예요.',en:'A Southeast Asian nation with deep Buddhist heritage.'}},
  'Cambodia':{iso2:'KH',ko:'캄보디아 왕국',en:'Kingdom of Cambodia',langs:['km'],gov:'constmon',econ:'cap',desc:{ko:'앙코르와트 유적으로 유명한 나라예요.',en:'Famous for the temples of Angkor Wat.'}},
  'Laos':{iso2:'LA',ko:'라오 인민민주공화국',en:"Lao People's Democratic Republic",langs:['lo'],gov:'onep',econ:'socmkt',desc:{ko:'동남아시아의 유일한 내륙국으로 메콩강이 흐르는 사회주의 국가예요.',en:'Southeast Asia\'s only landlocked country, a socialist state on the Mekong.'}},
  'Brunei':{iso2:'BN',ko:'브루나이 다루살람',en:'Brunei Darussalam',langs:['ms'],gov:'absmon',econ:'oil',desc:{ko:'보르네오섬의 석유가 풍부한 이슬람 왕국이에요.',en:'An oil-rich Islamic monarchy on Borneo.'}},
  'East Timor':{iso2:'TL',ko:'동티모르 민주공화국',en:'Democratic Republic of Timor-Leste',langs:['tet','pt'],gov:'semi',econ:'oil',desc:{ko:'21세기 초 독립한 동남아시아의 젊은 나라예요.',en:'A young Southeast Asian nation that gained independence in the early 2000s.'}},
  'Maldives':{iso2:'MV',ko:'몰디브 공화국',en:'Republic of Maldives',langs:['dv'],gov:'presrep',econ:'cap',desc:{ko:'인도양의 산호섬들로 이뤄진 휴양 국가예요.',en:'An Indian Ocean nation of coral atolls, a famed resort destination.'}},
  'Saudi Arabia':{iso2:'SA',ko:'사우디아라비아 왕국',en:'Kingdom of Saudi Arabia',langs:['ar'],gov:'absmon',econ:'oil',desc:{ko:'이슬람 성지와 막대한 석유 자원을 가진 나라예요.',en:'Home to Islam\'s holy cities and vast oil reserves.'}},
  'United Arab Emirates':{iso2:'AE',ko:'아랍에미리트',en:'United Arab Emirates',langs:['ar'],gov:'fedmon',econ:'oil',desc:{ko:'두바이·아부다비로 유명한 걸프 연안 연방국이에요.',en:'A Gulf federation known for Dubai and Abu Dhabi.'}},
  'Iran':{iso2:'IR',ko:'이란 이슬람공화국',en:'Islamic Republic of Iran',langs:['fa'],gov:'theo',econ:'mixed',desc:{ko:'페르시아 문명을 계승한 서아시아의 대국이에요.',en:'A West Asian nation heir to the Persian civilization.'}},
  'Iraq':{iso2:'IQ',ko:'이라크 공화국',en:'Republic of Iraq',langs:['ar'],gov:'fedparl',econ:'oil',desc:{ko:'메소포타미아 문명의 발상지예요.',en:'The cradle of the Mesopotamian civilization.'}},
  'Israel':{iso2:'IL',ko:'이스라엘국',en:'State of Israel',langs:['he','ar'],gov:'parlrep',econ:'cap',desc:{ko:'지중해 동안의 첨단기술 국가예요.',en:'A high-tech nation on the eastern Mediterranean.'}},
  'Jordan':{iso2:'JO',ko:'요르단 하심 왕국',en:'Hashemite Kingdom of Jordan',langs:['ar'],gov:'constmon',econ:'mixed',desc:{ko:'페트라 유적으로 유명한 서아시아의 왕국이에요.',en:'A West Asian kingdom famous for the ruins of Petra.'}},
  'Lebanon':{iso2:'LB',ko:'레바논 공화국',en:'Lebanese Republic',langs:['ar'],gov:'parlrep',econ:'mixed',desc:{ko:'지중해 동안의 다종교 국가예요.',en:'A multireligious country on the eastern Mediterranean.'}},
  'Syria':{iso2:'SY',ko:'시리아 아랍공화국',en:'Syrian Arab Republic',langs:['ar'],gov:'presrep',econ:'mixed',desc:{ko:'고대 도시 다마스쿠스를 품은 서아시아 국가예요.',en:'A West Asian country home to the ancient city of Damascus.'}},
  'Oman':{iso2:'OM',ko:'오만 술탄국',en:'Sultanate of Oman',langs:['ar'],gov:'absmon',econ:'oil',desc:{ko:'아라비아반도 남동부의 술탄국이에요.',en:'A sultanate on the southeastern Arabian Peninsula.'}},
  'Kuwait':{iso2:'KW',ko:'쿠웨이트국',en:'State of Kuwait',langs:['ar'],gov:'constmon',econ:'oil',desc:{ko:'걸프 연안의 석유 부국이에요.',en:'An oil-wealthy state on the Persian Gulf.'}},
  'Qatar':{iso2:'QA',ko:'카타르국',en:'State of Qatar',langs:['ar'],gov:'absmon',econ:'oil',desc:{ko:'천연가스가 풍부한 걸프의 반도 국가예요.',en:'A Gulf peninsula rich in natural gas.'}},
  'Bahrain':{iso2:'BH',ko:'바레인 왕국',en:'Kingdom of Bahrain',langs:['ar'],gov:'constmon',econ:'oil',desc:{ko:'걸프의 섬으로 이뤄진 왕국이에요.',en:'An island kingdom in the Persian Gulf.'}},
  'Yemen':{iso2:'YE',ko:'예멘 공화국',en:'Republic of Yemen',langs:['ar'],gov:'presrep',econ:'mixed',desc:{ko:'아라비아반도 남단의 나라예요.',en:'A country at the southern tip of the Arabian Peninsula.'}},
  'Turkey':{iso2:'TR',ko:'튀르키예 공화국',en:'Republic of Türkiye',langs:['tr'],gov:'presrep',econ:'cap',desc:{ko:'아시아와 유럽에 걸친 문명의 교차로예요.',en:'A crossroads of civilizations spanning Asia and Europe.'}},
  'Kazakhstan':{iso2:'KZ',ko:'카자흐스탄 공화국',en:'Republic of Kazakhstan',langs:['kk','ru'],gov:'presrep',econ:'cap',desc:{ko:'세계에서 가장 큰 내륙국이에요.',en:'The world\'s largest landlocked country.'}},
  'Uzbekistan':{iso2:'UZ',ko:'우즈베키스탄 공화국',en:'Republic of Uzbekistan',langs:['uz'],gov:'presrep',econ:'mixed',desc:{ko:'실크로드의 사마르칸트로 유명한 중앙아시아 국가예요.',en:'A Central Asian nation famed for Silk Road Samarkand.'}},
  'Turkmenistan':{iso2:'TM',ko:'투르크메니스탄',en:'Turkmenistan',langs:['ru'],gov:'presrep',econ:'oil',desc:{ko:'카라쿰 사막과 천연가스의 중앙아시아 국가예요.',en:'A Central Asian nation of the Karakum desert and natural gas.'}},
  'Kyrgyzstan':{iso2:'KG',ko:'키르기스 공화국',en:'Kyrgyz Republic',langs:['ru'],gov:'presrep',econ:'mixed',desc:{ko:'천산산맥의 산악 내륙국이에요.',en:'A mountainous landlocked country in the Tian Shan.'}},
  'Tajikistan':{iso2:'TJ',ko:'타지키스탄 공화국',en:'Republic of Tajikistan',langs:['ru'],gov:'presrep',econ:'mixed',desc:{ko:'파미르고원의 산악 국가예요.',en:'A mountainous country of the Pamir highlands.'}},
  'Afghanistan':{iso2:'AF',ko:'아프가니스탄',en:'Afghanistan',langs:['ps','fa'],gov:'theo',econ:'mixed',desc:{ko:'중앙아시아 산악 지대의 내륙국이에요.',en:'A landlocked country of Central Asian mountains.'}},
  'Georgia':{iso2:'GE',ko:'조지아',en:'Georgia',langs:['ka'],gov:'parlrep',econ:'cap',desc:{ko:'캅카스의 와인 발상지로 알려진 나라예요.',en:'A Caucasus nation known as a birthplace of wine.'}},
  'Armenia':{iso2:'AM',ko:'아르메니아 공화국',en:'Republic of Armenia',langs:['hy'],gov:'parlrep',econ:'cap',desc:{ko:'세계 최초로 기독교를 국교로 삼은 캅카스 국가예요.',en:'A Caucasus nation, the first to adopt Christianity as a state religion.'}},
  'Azerbaijan':{iso2:'AZ',ko:'아제르바이잔 공화국',en:'Republic of Azerbaijan',langs:['az'],gov:'presrep',econ:'oil',desc:{ko:'카스피해의 석유가 풍부한 캅카스 국가예요.',en:'A Caucasus nation rich in Caspian Sea oil.'}},

  // ===== 유럽 =====
  'United Kingdom':{iso2:'GB',ko:'그레이트브리튼 및 북아일랜드 연합왕국',en:'United Kingdom',langs:['en'],gov:'constmon',econ:'cap',desc:{ko:'산업혁명의 발상지이자 유럽의 섬나라예요.',en:'Birthplace of the Industrial Revolution, an island nation off Europe.'}},
  'France':{iso2:'FR',ko:'프랑스 공화국',en:'French Republic',langs:['fr'],gov:'semi',econ:'cap',desc:{ko:'예술·패션·요리로 유명한 서유럽의 중심국이에요.',en:'A Western European hub famed for art, fashion, and cuisine.'}},
  'Germany':{iso2:'DE',ko:'독일 연방공화국',en:'Federal Republic of Germany',langs:['de'],gov:'fedparl',econ:'socmkt2',desc:{ko:'유럽 최대 경제 규모의 제조 강국이에요.',en:'Europe\'s largest economy and a manufacturing powerhouse.'}},
  'Italy':{iso2:'IT',ko:'이탈리아 공화국',en:'Italian Republic',langs:['it'],gov:'parlrep',econ:'cap',desc:{ko:'로마 제국과 르네상스의 나라예요.',en:'Land of the Roman Empire and the Renaissance.'}},
  'Spain':{iso2:'ES',ko:'스페인 왕국',en:'Kingdom of Spain',langs:['es'],gov:'constmon',econ:'cap',desc:{ko:'이베리아반도의 정열적인 문화를 지닌 나라예요.',en:'An Iberian nation of passionate culture.'}},
  'Portugal':{iso2:'PT',ko:'포르투갈 공화국',en:'Portuguese Republic',langs:['pt'],gov:'parlrep',econ:'cap',desc:{ko:'대항해시대를 연 이베리아반도의 나라예요.',en:'The Iberian nation that launched the Age of Discovery.'}},
  'Netherlands':{iso2:'NL',ko:'네덜란드 왕국',en:'Kingdom of the Netherlands',langs:['nl'],gov:'constmon',econ:'cap',desc:{ko:'풍차와 운하, 낮은 땅으로 유명해요.',en:'Known for windmills, canals, and low-lying land.'}},
  'Belgium':{iso2:'BE',ko:'벨기에 왕국',en:'Kingdom of Belgium',langs:['nl','fr','de'],gov:'fedconst',econ:'cap',desc:{ko:'EU 본부가 있는 서유럽의 나라예요.',en:'A Western European nation hosting the EU headquarters.'}},
  'Switzerland':{iso2:'CH',ko:'스위스 연방',en:'Swiss Confederation',langs:['de','fr','it'],gov:'directdem',econ:'cap',desc:{ko:'알프스와 금융·시계로 유명한 중립국이에요.',en:'A neutral nation famed for the Alps, finance, and watches.'}},
  'Austria':{iso2:'AT',ko:'오스트리아 공화국',en:'Republic of Austria',langs:['de'],gov:'fedparl',econ:'cap',desc:{ko:'음악과 알프스로 유명한 중부유럽 국가예요.',en:'A Central European nation famed for music and the Alps.'}},
  'Sweden':{iso2:'SE',ko:'스웨덴 왕국',en:'Kingdom of Sweden',langs:['sv'],gov:'constmon',econ:'welfare',desc:{ko:'북유럽의 복지·디자인 강국이에요.',en:'A Nordic leader in welfare and design.'}},
  'Norway':{iso2:'NO',ko:'노르웨이 왕국',en:'Kingdom of Norway',langs:['no'],gov:'constmon',econ:'welfare',desc:{ko:'피오르와 석유로 부유한 북유럽 국가예요.',en:'A Nordic nation wealthy from fjords and oil.'}},
  'Denmark':{iso2:'DK',ko:'덴마크 왕국',en:'Kingdom of Denmark',langs:['da'],gov:'constmon',econ:'welfare',desc:{ko:'북유럽의 작지만 살기 좋은 나라예요.',en:'A small, highly livable Nordic country.'}},
  'Finland':{iso2:'FI',ko:'핀란드 공화국',en:'Republic of Finland',langs:['fi','sv'],gov:'parlrep',econ:'welfare',desc:{ko:'호수와 숲, 오로라로 유명한 북유럽 국가예요.',en:'A Nordic nation of lakes, forests, and auroras.'}},
  'Iceland':{iso2:'IS',ko:'아이슬란드',en:'Iceland',langs:['is'],gov:'parlrep',econ:'welfare',desc:{ko:'화산과 빙하, 지열의 북대서양 섬나라예요.',en:'A North Atlantic island of volcanoes, glaciers, and geothermal energy.'}},
  'Ireland':{iso2:'IE',ko:'아일랜드',en:'Ireland',langs:['en'],gov:'parlrep',econ:'cap',desc:{ko:'초록 들판과 켈트 문화의 섬나라예요.',en:'An island of green fields and Celtic culture.'}},
  'Poland':{iso2:'PL',ko:'폴란드 공화국',en:'Republic of Poland',langs:['pl'],gov:'parlrep',econ:'cap',desc:{ko:'중부유럽의 역사 깊은 나라예요.',en:'A Central European nation with a deep history.'}},
  'Ukraine':{iso2:'UA',ko:'우크라이나',en:'Ukraine',langs:['uk'],gov:'semi',econ:'cap',desc:{ko:'비옥한 흑토와 밀 생산으로 알려진 동유럽 국가예요.',en:'An Eastern European nation known for fertile soil and wheat.'}},
  'Russia':{iso2:'RU',ko:'러시아 연방',en:'Russian Federation',langs:['ru'],gov:'fedpres',econ:'mixed',desc:{ko:'세계에서 가장 영토가 넓은 나라예요.',en:'The largest country in the world by area.'}},
  'Greece':{iso2:'GR',ko:'그리스 공화국',en:'Hellenic Republic',langs:['el'],gov:'parlrep',econ:'cap',desc:{ko:'서양 문명과 민주주의의 발상지예요.',en:'The birthplace of Western civilization and democracy.'}},
  'Czechia':{iso2:'CZ',ko:'체코 공화국',en:'Czech Republic',langs:['cs'],gov:'parlrep',econ:'cap',desc:{ko:'프라하로 유명한 중부유럽 국가예요.',en:'A Central European nation famed for Prague.'}},
  'Hungary':{iso2:'HU',ko:'헝가리',en:'Hungary',langs:['hu'],gov:'parlrep',econ:'cap',desc:{ko:'다뉴브강과 부다페스트의 중부유럽 국가예요.',en:'A Central European nation of the Danube and Budapest.'}},
  'Romania':{iso2:'RO',ko:'루마니아',en:'Romania',langs:['ro'],gov:'semi',econ:'cap',desc:{ko:'카르파티아 산맥과 트란실바니아의 나라예요.',en:'Land of the Carpathians and Transylvania.'}},
  'Bulgaria':{iso2:'BG',ko:'불가리아 공화국',en:'Republic of Bulgaria',langs:['bg'],gov:'parlrep',econ:'cap',desc:{ko:'장미와 요구르트로 유명한 발칸 국가예요.',en:'A Balkan nation famed for roses and yogurt.'}},
  'Republic of Serbia':{iso2:'RS',ko:'세르비아 공화국',en:'Republic of Serbia',langs:['sr'],gov:'parlrep',econ:'cap',desc:{ko:'발칸반도 중앙의 내륙국이에요.',en:'A landlocked nation in the heart of the Balkans.'}},
  'Croatia':{iso2:'HR',ko:'크로아티아 공화국',en:'Republic of Croatia',langs:['hr'],gov:'parlrep',econ:'cap',desc:{ko:'아드리아해의 아름다운 해안으로 유명해요.',en:'Famous for its beautiful Adriatic coast.'}},
  'Slovakia':{iso2:'SK',ko:'슬로바키아 공화국',en:'Slovak Republic',langs:['sk'],gov:'parlrep',econ:'cap',desc:{ko:'타트라 산맥의 중부유럽 내륙국이에요.',en:'A Central European landlocked nation of the Tatra Mountains.'}},
  'Slovenia':{iso2:'SI',ko:'슬로베니아 공화국',en:'Republic of Slovenia',langs:['sl'],gov:'parlrep',econ:'cap',desc:{ko:'알프스와 아드리아해가 만나는 작은 나라예요.',en:'A small nation where the Alps meet the Adriatic.'}},
  'Lithuania':{iso2:'LT',ko:'리투아니아 공화국',en:'Republic of Lithuania',langs:['lt'],gov:'semi',econ:'cap',desc:{ko:'발트해 연안의 나라예요.',en:'A Baltic Sea nation.'}},
  'Latvia':{iso2:'LV',ko:'라트비아 공화국',en:'Republic of Latvia',langs:['lv'],gov:'parlrep',econ:'cap',desc:{ko:'발트 3국 중 가운데에 있는 나라예요.',en:'The central of the three Baltic states.'}},
  'Estonia':{iso2:'EE',ko:'에스토니아 공화국',en:'Republic of Estonia',langs:['et'],gov:'parlrep',econ:'cap',desc:{ko:'디지털 정부로 유명한 발트 국가예요.',en:'A Baltic nation famed for its digital government.'}},
  'Albania':{iso2:'AL',ko:'알바니아 공화국',en:'Republic of Albania',langs:['sq'],gov:'parlrep',econ:'cap',desc:{ko:'발칸반도 서남부의 나라예요.',en:'A nation in the southwestern Balkans.'}},
  'North Macedonia':{iso2:'MK',ko:'북마케도니아 공화국',en:'Republic of North Macedonia',langs:['mk'],gov:'parlrep',econ:'cap',desc:{ko:'발칸반도의 내륙국이에요.',en:'A landlocked Balkan nation.'}},
  'Luxembourg':{iso2:'LU',ko:'룩셈부르크 대공국',en:'Grand Duchy of Luxembourg',langs:['fr','de'],gov:'constmon',econ:'cap',desc:{ko:'금융이 발달한 작은 대공국이에요.',en:'A small grand duchy with a strong financial sector.'}},
  'Malta':{iso2:'MT',ko:'몰타 공화국',en:'Republic of Malta',langs:['mt','en'],gov:'parlrep',econ:'cap',desc:{ko:'지중해 한가운데의 섬나라예요.',en:'An island nation in the middle of the Mediterranean.'}},
  'Cyprus':{iso2:'CY',ko:'키프로스 공화국',en:'Republic of Cyprus',langs:['el','tr'],gov:'presrep',econ:'cap',desc:{ko:'지중해 동부의 섬나라예요.',en:'An island nation in the eastern Mediterranean.'}},

  // ===== 아프리카 =====
  'Egypt':{iso2:'EG',ko:'이집트 아랍공화국',en:'Arab Republic of Egypt',langs:['ar'],gov:'presrep',econ:'mixed',desc:{ko:'나일강과 피라미드의 고대 문명 국가예요.',en:'A land of ancient civilization, the Nile, and the pyramids.'}},
  'Nigeria':{iso2:'NG',ko:'나이지리아 연방공화국',en:'Federal Republic of Nigeria',langs:['en'],gov:'fedpres',econ:'cap',desc:{ko:'아프리카에서 인구가 가장 많은 나라예요.',en:'The most populous country in Africa.'}},
  'South Africa':{iso2:'ZA',ko:'남아프리카 공화국',en:'Republic of South Africa',langs:['zu','af','en'],gov:'parlrep',econ:'cap',desc:{ko:'아프리카 최남단의 다문화 국가예요.',en:'A multicultural nation at Africa\'s southern tip.'}},
  'Ethiopia':{iso2:'ET',ko:'에티오피아 연방민주공화국',en:'Federal Democratic Republic of Ethiopia',langs:['am'],gov:'fedparl',econ:'mixed',desc:{ko:'커피의 원산지이자 오랜 독립 역사를 지닌 나라예요.',en:'Birthplace of coffee, with a long history of independence.'}},
  'Kenya':{iso2:'KE',ko:'케냐 공화국',en:'Republic of Kenya',langs:['sw','en'],gov:'presrep',econ:'cap',desc:{ko:'사바나 야생동물과 마라톤으로 유명해요.',en:'Famed for savanna wildlife and marathon runners.'}},
  'Morocco':{iso2:'MA',ko:'모로코 왕국',en:'Kingdom of Morocco',langs:['ar','ber'],gov:'constmon',econ:'cap',desc:{ko:'사막과 지중해가 만나는 북아프리카 국가예요.',en:'A North African nation where desert meets the Mediterranean.'}},
  'Algeria':{iso2:'DZ',ko:'알제리 인민민주공화국',en:"People's Democratic Republic of Algeria",langs:['ar','ber'],gov:'presrep',econ:'mixed',desc:{ko:'아프리카에서 가장 영토가 넓은 나라예요.',en:'The largest country in Africa by area.'}},
  'Ghana':{iso2:'GH',ko:'가나 공화국',en:'Republic of Ghana',langs:['en'],gov:'presrep',econ:'cap',desc:{ko:'서아프리카의 금과 카카오 생산국이에요.',en:'A West African producer of gold and cocoa.'}},
  'United Republic of Tanzania':{iso2:'TZ',ko:'탄자니아 연합공화국',en:'United Republic of Tanzania',langs:['sw','en'],gov:'presrep',econ:'mixed',desc:{ko:'킬리만자로와 세렝게티로 유명해요.',en:'Famed for Kilimanjaro and the Serengeti.'}},
  'Madagascar':{iso2:'MG',ko:'마다가스카르 공화국',en:'Republic of Madagascar',langs:['mg','fr'],gov:'semi',econ:'mixed',desc:{ko:'고유종이 가득한 인도양의 거대한 섬나라예요.',en:'A huge Indian Ocean island full of endemic species.'}},
  'Democratic Republic of the Congo':{iso2:'CD',ko:'콩고 민주공화국',en:'Democratic Republic of the Congo',langs:['fr'],gov:'semi',econ:'mixed',desc:{ko:'광물이 풍부한 중앙아프리카의 대국이에요.',en:'A vast mineral-rich Central African nation.'}},

  // ===== 북아메리카 =====
  'United States of America':{iso2:'US',ko:'아메리카 합중국',en:'United States of America',langs:['en'],gov:'fedpres',econ:'cap',desc:{ko:'50개 주로 이뤄진 세계적 경제·군사 강국이에요.',en:'A global economic and military power of 50 states.'}},
  'Canada':{iso2:'CA',ko:'캐나다',en:'Canada',langs:['en','fr'],gov:'fedconst',econ:'cap',desc:{ko:'광활한 자연을 가진 북미의 큰 나라예요.',en:'A vast North American nation of sweeping wilderness.'}},
  'Mexico':{iso2:'MX',ko:'멕시코 합중국',en:'United Mexican States',langs:['es'],gov:'fedpres',econ:'cap',desc:{ko:'마야·아즈텍 문명을 계승한 북미 국가예요.',en:'A North American nation heir to Maya and Aztec civilizations.'}},
  'Cuba':{iso2:'CU',ko:'쿠바 공화국',en:'Republic of Cuba',langs:['es'],gov:'comm',econ:'plan',desc:{ko:'카리브해의 사회주의 섬나라예요.',en:'A socialist island nation in the Caribbean.'}},
  'Guatemala':{iso2:'GT',ko:'과테말라 공화국',en:'Republic of Guatemala',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'마야 문명 유적이 많은 중미 국가예요.',en:'A Central American nation rich in Maya ruins.'}},
  'Costa Rica':{iso2:'CR',ko:'코스타리카 공화국',en:'Republic of Costa Rica',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'생태관광과 군대 없는 나라로 유명해요.',en:'Famed for ecotourism and having no standing army.'}},
  'Panama':{iso2:'PA',ko:'파나마 공화국',en:'Republic of Panama',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'대서양과 태평양을 잇는 운하의 나라예요.',en:'Home of the canal linking the Atlantic and Pacific.'}},
  'Dominican Republic':{iso2:'DO',ko:'도미니카 공화국',en:'Dominican Republic',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'히스파니올라섬 동부의 카리브 국가예요.',en:'A Caribbean nation on the eastern half of Hispaniola.'}},
  'Greenland':{iso2:'GL',ko:'그린란드',en:'Greenland',langs:['da'],gov:'dep',econ:'mixed',desc:{ko:'세계에서 가장 큰 섬으로 대부분 얼음으로 덮여 있어요.',en:'The world\'s largest island, mostly covered by ice.'}},

  // ===== 남아메리카 =====
  'Brazil':{iso2:'BR',ko:'브라질 연방공화국',en:'Federative Republic of Brazil',langs:['pt'],gov:'fedpres',econ:'cap',desc:{ko:'아마존과 축구, 삼바의 남미 최대 국가예요.',en:'South America\'s largest nation, of the Amazon, football, and samba.'}},
  'Argentina':{iso2:'AR',ko:'아르헨티나 공화국',en:'Argentine Republic',langs:['es'],gov:'fedpres',econ:'cap',desc:{ko:'팜파스 초원과 탱고로 유명한 남미 국가예요.',en:'A South American nation of the Pampas and tango.'}},
  'Chile':{iso2:'CL',ko:'칠레 공화국',en:'Republic of Chile',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'안데스와 태평양 사이 길게 뻗은 나라예요.',en:'A long ribbon of a country between the Andes and Pacific.'}},
  'Peru':{iso2:'PE',ko:'페루 공화국',en:'Republic of Peru',langs:['es','qu'],gov:'presrep',econ:'cap',desc:{ko:'잉카 문명과 마추픽추의 나라예요.',en:'Land of the Inca and Machu Picchu.'}},
  'Colombia':{iso2:'CO',ko:'콜롬비아 공화국',en:'Republic of Colombia',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'커피와 카리브·태평양 해안을 가진 나라예요.',en:'A nation of coffee and both Caribbean and Pacific coasts.'}},
  'Venezuela':{iso2:'VE',ko:'베네수엘라 볼리바르공화국',en:'Bolivarian Republic of Venezuela',langs:['es'],gov:'fedpres',econ:'oil',desc:{ko:'세계 최대 석유 매장량을 가진 남미 국가예요.',en:'A South American nation with the world\'s largest oil reserves.'}},
  'Ecuador':{iso2:'EC',ko:'에콰도르 공화국',en:'Republic of Ecuador',langs:['es'],gov:'presrep',econ:'oil',desc:{ko:'적도와 갈라파고스 제도의 나라예요.',en:'Land of the equator and the Galápagos Islands.'}},
  'Bolivia':{iso2:'BO',ko:'볼리비아 다민족국',en:'Plurinational State of Bolivia',langs:['es','qu'],gov:'presrep',econ:'mixed',desc:{ko:'우유니 소금사막과 안데스 고원의 나라예요.',en:'Land of the Uyuni salt flats and Andean highlands.'}},
  'Paraguay':{iso2:'PY',ko:'파라과이 공화국',en:'Republic of Paraguay',langs:['es','gn'],gov:'presrep',econ:'cap',desc:{ko:'남미 중앙의 내륙국이에요.',en:'A landlocked nation in the heart of South America.'}},
  'Uruguay':{iso2:'UY',ko:'우루과이 동방공화국',en:'Oriental Republic of Uruguay',langs:['es'],gov:'presrep',econ:'cap',desc:{ko:'남미에서 가장 안정적인 작은 나라예요.',en:'One of South America\'s smallest and most stable nations.'}},

  // ===== 오세아니아 =====
  'Australia':{iso2:'AU',ko:'오스트레일리아 연방',en:'Commonwealth of Australia',langs:['en'],gov:'fedconst',econ:'cap',desc:{ko:'대륙이자 나라인 남반구의 큰 섬이에요.',en:'A country that is also a continent, a great southern island.'}},
  'New Zealand':{iso2:'NZ',ko:'뉴질랜드',en:'New Zealand',langs:['en','mi'],gov:'constmon',econ:'cap',desc:{ko:'초록 자연과 마오리 문화의 섬나라예요.',en:'An island nation of green landscapes and Maori culture.'}},
  'Papua New Guinea':{iso2:'PG',ko:'파푸아뉴기니 독립국',en:'Independent State of Papua New Guinea',langs:['en','tpi'],gov:'constmon',econ:'mixed',desc:{ko:'수백 개 언어가 쓰이는 태평양의 섬나라예요.',en:'A Pacific island nation where hundreds of languages are spoken.'}},
  'Fiji':{iso2:'FJ',ko:'피지 공화국',en:'Republic of Fiji',langs:['en','fj'],gov:'parlrep',econ:'cap',desc:{ko:'남태평양의 아름다운 섬 관광국이에요.',en:'A beautiful South Pacific island tourism nation.'}},
  'Samoa':{iso2:'WS',ko:'사모아 독립국',en:'Independent State of Samoa',langs:['sm','en'],gov:'parlrep',econ:'mixed',desc:{ko:'폴리네시아 문화의 남태평양 섬나라예요.',en:'A South Pacific island nation of Polynesian culture.'}},
  'Tonga':{iso2:'TO',ko:'통가 왕국',en:'Kingdom of Tonga',langs:['to','en'],gov:'constmon',econ:'mixed',desc:{ko:'폴리네시아의 유일한 왕국이에요.',en:'The only kingdom in Polynesia.'}},
  'Vanuatu':{iso2:'VU',ko:'바누아투 공화국',en:'Republic of Vanuatu',langs:['en','fr'],gov:'parlrep',econ:'mixed',desc:{ko:'남태평양 화산 군도 국가예요.',en:'A South Pacific volcanic archipelago nation.'}},
  'Solomon Islands':{iso2:'SB',ko:'솔로몬 제도',en:'Solomon Islands',langs:['en'],gov:'constmon',econ:'mixed',desc:{ko:'남태평양의 섬 국가예요.',en:'A South Pacific island nation.'}},
};

// 국가 정보를 언어에 맞춰 해석해 반환. 표에 없으면 null.
export function countryInfo(name, lang){
  const d=COUNTRY[name]; if(!d)return null; const i=lang==='en'?1:0;
  return {
    iso2:d.iso2, flag:flagEmoji(d.iso2),
    name:i?d.en:d.ko, official:i?d.ko:d.en,
    langs:(d.langs||[]).slice(0,3).map(c=>(LANG[c]?LANG[c][i]:c)).filter(Boolean),
    gov:d.gov&&GOV[d.gov]?GOV[d.gov][i]:'', econ:d.econ&&ECON[d.econ]?ECON[d.econ][i]:'',
    desc:d.desc?(i?d.desc.en:d.desc.ko):'',
  };
}
