-- Shared component tokens and anonymous, moderated reviews.
create table if not exists public.component_design (
  component_key text not null,
  property text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (component_key, property)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  rating smallint not null check (rating between 1 and 5),
  body text not null check (char_length(body) between 1 and 500),
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  moderation_reason text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists reviews_status_created_at_idx on public.reviews(status, created_at desc);
alter table public.component_design enable row level security;
alter table public.reviews enable row level security;
drop policy if exists "component design is not directly readable" on public.component_design;
drop policy if exists "reviews are not directly readable" on public.reviews;

create or replace function public.list_component_design(p_component_key text)
returns table(property text, value jsonb)
language sql security definer set search_path = public
as $$
  select cd.property, cd.value from public.component_design cd
  where cd.component_key = p_component_key order by cd.property;
$$;

create or replace function public.admin_save_component_design(p_pw text, p_component_key text, p_values jsonb)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  allowed text[] := array['color','backgroundColor','fontFamily','fontSize','fontWeight','lineHeight','letterSpacing','padding','margin','borderRadius','borderColor','borderWidth','opacity','display'];
  item record;
begin
  if not public.admin_check(p_pw) then raise exception '관리자 인증이 필요합니다.'; end if;
  if p_component_key is null or p_component_key !~ '^[a-z0-9_-]{1,40}$' then raise exception '잘못된 컴포넌트 키입니다.'; end if;
  if jsonb_typeof(p_values) <> 'object' then raise exception '디자인 값은 객체여야 합니다.'; end if;
  for item in select key, value from jsonb_each(p_values) loop
    if not (item.key = any(allowed)) then raise exception '허용되지 않은 디자인 속성입니다: %', item.key; end if;
    if jsonb_typeof(item.value) <> 'string' or char_length(item.value #>> '{}') > 160 then raise exception '디자인 값이 올바르지 않습니다.'; end if;
  end loop;
  delete from public.component_design where component_key = p_component_key;
  insert into public.component_design(component_key, property, value)
  select p_component_key, key, value from jsonb_each(p_values);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_delete_component_design(p_pw text, p_component_key text)
returns jsonb language plpgsql security definer set search_path = public
as $$
begin
  if not public.admin_check(p_pw) then raise exception '관리자 인증이 필요합니다.'; end if;
  delete from public.component_design where component_key = p_component_key;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.submit_review(p_rating integer, p_body text)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  clean_body text;
  normalized text;
  blocked text[] := array['시발','씨발','병신','좆','개새끼','꺼져','죽어','멍청이','한남','한녀','페미년','틀딱','등신','지랄','fuck','shit','bitch','idiot','stupid'];
  term text;
  review_id bigint;
begin
  if p_rating is null or p_rating < 1 or p_rating > 5 then return jsonb_build_object('ok', false, 'error', '별점은 1점에서 5점 사이여야 합니다.'); end if;
  clean_body := btrim(regexp_replace(coalesce(p_body, ''), '<[^>]*>', '', 'g'));
  clean_body := regexp_replace(clean_body, '\s+', ' ', 'g');
  if char_length(clean_body) < 1 or char_length(clean_body) > 500 then return jsonb_build_object('ok', false, 'error', '리뷰는 1자 이상 500자 이하로 작성해 주세요.'); end if;
  normalized := lower(clean_body);
  foreach term in array blocked loop
    if position(lower(term) in normalized) > 0 then return jsonb_build_object('ok', false, 'error', '공격적이거나 부적절한 표현은 등록할 수 없습니다.'); end if;
  end loop;
  insert into public.reviews(rating, body, status) values (p_rating, clean_body, 'pending') returning id into review_id;
  return jsonb_build_object('ok', true, 'id', review_id, 'status', 'pending');
end;
$$;

create or replace function public.list_reviews()
returns table(id bigint, rating smallint, body text, created_at timestamptz)
language sql security definer set search_path = public
as $$
  select r.id, r.rating, r.body, r.created_at from public.reviews r
  where r.status = 'published' order by r.created_at desc;
$$;

create or replace function public.admin_list_reviews(p_pw text)
returns table(id bigint, rating smallint, body text, status text, moderation_reason text, created_at timestamptz, reviewed_at timestamptz)
language plpgsql security definer set search_path = public
as $$
begin
  if not public.admin_check(p_pw) then raise exception '관리자 인증이 필요합니다.'; end if;
  return query select r.id, r.rating, r.body, r.status, r.moderation_reason, r.created_at, r.reviewed_at from public.reviews r order by r.created_at desc;
end;
$$;

create or replace function public.admin_set_review_status(p_pw text, p_id bigint, p_status text)
returns jsonb language plpgsql security definer set search_path = public
as $$
begin
  if not public.admin_check(p_pw) then raise exception '관리자 인증이 필요합니다.'; end if;
  if p_status not in ('pending', 'published', 'rejected') then raise exception '잘못된 리뷰 상태입니다.'; end if;
  update public.reviews set status = p_status, reviewed_at = case when p_status = 'pending' then null else now() end where id = p_id;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on table public.component_design from anon, authenticated;
revoke all on table public.reviews from anon, authenticated;
grant execute on function public.list_component_design(text) to anon, authenticated;
grant execute on function public.submit_review(integer, text) to anon, authenticated;
grant execute on function public.list_reviews() to anon, authenticated;
grant execute on function public.admin_save_component_design(text, text, jsonb) to anon, authenticated;
grant execute on function public.admin_delete_component_design(text, text) to anon, authenticated;
grant execute on function public.admin_list_reviews(text) to anon, authenticated;
grant execute on function public.admin_set_review_status(text, bigint, text) to anon, authenticated;
